"""Fixture ingest for the V-model chain.

One entry point, :func:`seed_vmodel`, loads the committed fixtures under
``backend/api/vmodel_fixtures/`` into the ``vm_*`` collections.

It is idempotent by *rewrite*, not by skip: every set is written in place at its own fixed
version with upserts, and anything at that version which is no longer in the fixture is
pruned. Calling it twice therefore leaves exactly the same database, and editing a fixture
and restarting actually refreshes the stored documents rather than leaving stale ones
behind. ``reset=True`` drops the ``vm_*`` collections first.

Both callers - application startup and ``POST /api/v1/vmodel/seed`` - go through this same
function; ``reset`` is the only difference between them. Startup goes through
:func:`seed_vmodel_safe`, which additionally guarantees that a fixture problem cannot stop
the API from booting.

Everything ingested here is generated by acc_project - the requirement register, the test
specifications, the signal catalogue, the implementation sources and the verdicts. Nothing is
authored in this repository. ``vmodel_fixtures/tools/build_vmodel_fixtures.py`` regenerates
the lot; ``vmodel_fixtures/README.md`` records the digests.
"""

import json
import logging
from pathlib import Path
from typing import Any

from pymongo.database import Database

from .models_vmodel import BaselineCounts
from .vmodel_ingest import (
    FIXTURES_DIR,
    REQUIREMENTS_FIXTURE,
    IngestError,
    ingest_requirements_set,
    publish_baseline,
)
from .vmodel_ingest_chain import (
    compute_req_links,
    ingest_results,
    ingest_signals,
    ingest_test_impls,
    ingest_test_specs,
    ingest_traces,
    tc_id_index,
)

logger = logging.getLogger(__name__)

TEST_SPECS_FIXTURE = FIXTURES_DIR / "test_specs" / "acc-system-test-specs.json"
TEST_IMPLS_FIXTURE = FIXTURES_DIR / "test_impls" / "acc-test-impls.json"
SIGNALS_FIXTURE = FIXTURES_DIR / "signals" / "acc-signal-catalogue.json"
TRACES_FIXTURE = FIXTURES_DIR / "results" / "acc-traces.json"
VERDICTS_FIXTURE = FIXTURES_DIR / "results" / "acc-verdicts.json"

# One version per artifact kind: acc_project has published exactly one of each. Older
# requirement sets (the all-Draft BL-0001/BL-0002 register) were not recoverable, and a
# second version is not synthesised to make the version dimension look busy.
SEED_VERSION = "v0001"
SEED_BASELINE_ID = "BL-0001"
SEED_SOURCE_LABEL = "acc_project Reqs/export/json/acc-system-requirements.json"

VM_COLLECTIONS = (
    "vm_artifact_sets",
    "vm_requirements",
    "vm_test_specs",
    "vm_test_impls",
    "vm_signals",
    "vm_baselines",
    "vm_traces",
    "vm_run_traces",
    "vm_results",
    "vm_reports",
)


def load_fixture(path: Path) -> Any:
    """Read and parse a JSON fixture. Raises :class:`IngestError` naming the file on failure."""
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise IngestError(f"Fixture {path.name} could not be read: {exc}") from exc


def reset_vmodel(mongo: Database[dict[str, Any]]) -> None:
    """Drop every ``vm_*`` collection. Never touches ``tests`` or ``devices``."""
    for name in VM_COLLECTIONS:
        mongo.drop_collection(name)
    logger.warning("Dropped %d V-model collections on reset", len(VM_COLLECTIONS))


def collection_counts(mongo: Database[dict[str, Any]]) -> dict[str, int]:
    """Document count per V-model collection - the seed endpoint's response body."""
    return {name: mongo[name].count_documents({}) for name in VM_COLLECTIONS}


def drop_legacy_artifact_sets(mongo: Database[dict[str, Any]]) -> int:
    """Remove registry documents written before the artifact-set key was scoped by kind.

    The old key was the bare version, so all four kinds wrote ``_id: "v0001"`` and
    overwrote each other, leaving a single survivor with no ``artifact_version`` field.
    Nothing reads those documents, but they would inflate the collection count forever on
    any database seeded by the buggy version, so the seed cleans up after itself.
    """
    deleted = mongo.vm_artifact_sets.delete_many({"artifact_version": {"$exists": False}})
    if deleted.deleted_count:
        logger.warning(
            "Removed %d legacy artifact-set documents keyed on the bare version",
            deleted.deleted_count,
        )
    return int(deleted.deleted_count)


def seed_vmodel(mongo: Database[dict[str, Any]], reset: bool = False) -> dict[str, int]:
    """Load every committed fixture into Mongo and return per-collection document counts."""
    if reset:
        reset_vmodel(mongo)

    drop_legacy_artifact_sets(mongo)

    if not FIXTURES_DIR.exists():
        logger.warning("V-model fixtures directory not found: %s", FIXTURES_DIR)
        return collection_counts(mongo)

    requirements_set, created = ingest_requirements_set(
        mongo,
        load_fixture(REQUIREMENTS_FIXTURE),
        source_label=SEED_SOURCE_LABEL,
        created_by="vmodel-seed",
        forced_version=SEED_VERSION,
    )
    requirements_version = str(requirements_set["artifact_version"])
    logger.info(
        "Requirements %s as %s (%d items)",
        "ingested" if created else "refreshed",
        requirements_version,
        requirements_set["item_count"],
    )

    specs_set = ingest_test_specs(
        mongo,
        load_fixture(TEST_SPECS_FIXTURE),
        SEED_VERSION,
        "acc_project TestSpecs/acc-system-test-specs.json",
    )
    spec_docs = list(mongo.vm_test_specs.find({"artifact_version": SEED_VERSION}))
    tc_by_req = tc_id_index(spec_docs)

    impls_set = ingest_test_impls(
        mongo,
        load_fixture(TEST_IMPLS_FIXTURE),
        SEED_VERSION,
        "acc_project TestImpl (registry + module sources)",
        tc_by_req,
    )
    signals_set = ingest_signals(
        mongo,
        load_fixture(SIGNALS_FIXTURE),
        SEED_VERSION,
        "acc_project Reqs/export/json/acc-signal-catalogue.json",
    )

    traces = ingest_traces(mongo, load_fixture(TRACES_FIXTURE))
    trace_index = {str(item["source_path"]): item for item in traces}
    result_count = ingest_results(
        mongo,
        load_fixture(VERDICTS_FIXTURE),
        trace_index,
        tc_by_req,
        SEED_BASELINE_ID,
    )
    logger.info("Ingested %d traces and %d verdicts", len(traces), result_count)

    req_links = compute_req_links(spec_docs)
    publish_baseline(
        mongo,
        baseline_id=SEED_BASELINE_ID,
        label="acc-system friday demo baseline",
        versions={
            "requirements": requirements_version,
            "test_specs": str(specs_set["artifact_version"]),
            "test_impl": str(impls_set["artifact_version"]),
            "signal_catalog": str(signals_set["artifact_version"]),
        },
        counts=BaselineCounts(
            requirements=int(requirements_set["item_count"]),
            test_cases=int(specs_set["item_count"]),
            impls=int(impls_set["item_count"]),
            covered_requirements=len(req_links),
        ),
        req_links=req_links,
        set_hashes={
            "requirements": str(requirements_set["canonical_sha256"]),
            "test_specs": str(specs_set["canonical_sha256"]),
            "test_impl": str(impls_set["canonical_sha256"]),
            "signal_catalog": str(signals_set["canonical_sha256"]),
        },
        notes=(
            "Single baseline. acc_project has published one version of each artifact set; "
            "the historical all-Draft requirement registers were not recoverable and are "
            "deliberately not synthesised."
        ),
    )

    return collection_counts(mongo)


def seed_vmodel_safe(mongo: Database[dict[str, Any]]) -> None:
    """Startup wrapper: seed, but never let a fixture problem block application boot.

    The catch is deliberately unbounded. The previous clause listed the exception types the
    ingest was expected to raise, which meant an unanticipated one - a ``pymongo``
    ``BulkWriteError``, as it turned out - escaped into the lifespan and the whole API
    refused to start over demo fixtures. Nothing loaded here is required to serve Tests,
    Devices or Lookups, so a failure degrades the V-model pages and nothing else.
    """
    try:
        seed_vmodel(mongo)
    except Exception:  # noqa: BLE001 - a fixture load must never stop the API booting
        logger.exception("V-model seeding failed; starting without V-model fixtures")
