FROM python:3.12-slim

ENV DEBIAN_FRONTEND="noninteractive"
ENV PYTHONUNBUFFERED=1
ENV PYTHONIOENCODING=UTF-8

WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["streamlit", "run", "main.py", "--server.port", "80", "--server.address", "0.0.0.0"]
