name: backend
language: python
variables:
  - name: MONGO_USER
    inputType: Secret
    multiline: false
    defaultValue: MONGO_USER
    required: true
  - name: MONGO_PASSWORD
    inputType: Secret
    multiline: false
    defaultValue: MONGO_PASSWORD
    required: true
  - name: MONGO_HOST
    inputType: FreeText
    multiline: false
    defaultValue: mongodb
    required: true
  - name: INFLUXDB_USER
    inputType: Secret
    multiline: false
    defaultValue: INFLUXDB_USER
    required: true
  - name: INFLUXDB_PASSWORD
    inputType: Secret
    multiline: false
    defaultValue: INFLUXDB_PASSWORD
    required: true
  - name: INFLUXDB_HOST
    inputType: FreeText
    multiline: false
    defaultValue: influxdb
    required: true
  - name: INFLUXDB_PORT
    inputType: FreeText
    multiline: false
    defaultValue: 8086
    required: true
  - name: CONFIG_API_URL
    inputType: FreeText
    multiline: false
    required: true
  - name: MEASUREMENTS_URL
    inputType: FreeText
    multiline: false
    defaultValue: https://query-ui-quixers-testrigdemodatawarehouse-prod.az-france-0.app.quix.io/
    required: false
  - name: DATA_LAKE_V2_TOPIC_NAME
    inputType: FreeText
    multiline: false
    defaultValue: mdf_file_test_ludvik_v2
    required: false
  - name: ANALYTICS_URL
    inputType: FreeText
    multiline: false
    defaultValue: https://marimo-analysis-quixers-advancedanalyticsnew-new.az-france-0.app.quix.io
    required: false
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
