"""Render the ten test implementations, one `.py` per definition, and upload them.

Each module is STANDALONE: the blob holds one file and a runner fetches one
file, so a shared library it could import does not exist at the far end. The
shared half is therefore in the template below and the per-test-case half is in
`implementation_cases.py`.

A module reads its run's samples from the lake through the QuixLake `/query`
endpoint, by `run_id` alone. The table partitions by
`platform/work_order/run_id` and carries no test-definition level — one run
fulfils several definitions — so `run_id` is the whole address.

The evidence keys match the `measured` column of `out/manifest.csv` exactly, so
the expected numbers and the achieved numbers compare without a mapping.
"""

from __future__ import annotations

import json
from pathlib import Path
from string import Template

from seed import push, sources
from seed.implementation_cases import BMS_STATE, CASES

OUT_DIR = Path(__file__).resolve().parents[1] / "out" / "impl"

_TEMPLATE = Template(
    '''"""$tc_id — $title

Generated by `battery-trace-gen/seed/implementations.py`. Do not edit it here;
regenerate. Covers $req_ids.

$rule

    evaluate(run_id, table) -> {"verdict": "PASS" | "FAIL", "evidence": {...}}

The evidence keys are the ones `out/manifest.csv` names for this test case.

The samples come from the lake by `run_id` alone: the table partitions by
platform / work order / run, and carries no test-definition level.
"""

from __future__ import annotations

import csv
import io
import os

import numpy as np
import requests

TC_ID = "$tc_id"
REQ_IDS = $req_id_list
#: The first name is the grid; every other signal is held onto its raster.
SIGNALS = $signal_list
#: Every number this test enforces. Each one is the requirement's own parameter
#: or the tolerance the test specification states.
LIMITS = $limits
$states
#: QuixLake's SQL endpoint and the bearer it takes (`api/api/services/lake.py`).
URL_VARIABLES = ("Quix__Lakehouse__Query__Url", "QUIX_LAKE_URL")
TOKEN_VARIABLES = ("Quix__Lakehouse__Query__AuthToken", "Quix__Sdk__Token")
TIMEOUT_SECONDS = 120.0


def _first_env(names):
    for name in names:
        value = os.environ.get(name, "").strip()
        if value:
            return value
    raise RuntimeError(f"none of {names} is set, so the lake cannot be reached")


def _query(sql):
    """Run one statement against QuixLake and read its CSV answer."""
    response = requests.post(
        _first_env(URL_VARIABLES).rstrip("/") + "/query",
        params={"union_by_name": "true"},
        data=sql.encode("utf-8"),
        headers={
            "Authorization": "Bearer " + _first_env(TOKEN_VARIABLES),
            "Content-Type": "text/plain",
            "Accept": "text/csv",
        },
        timeout=TIMEOUT_SECONDS,
    )
    response.raise_for_status()
    return list(csv.DictReader(io.StringIO(response.text)))


def _series(run_id, table):
    """`{signal: (timestamps in ms, values)}` for this test case's signals."""
    names = ", ".join("'" + name + "'" for name in SIGNALS)
    rows = _query(
        "SELECT ts_ms, signal, value FROM " + table
        + " WHERE run_id = '" + run_id.replace("'", "''") + "'"
        + " AND signal IN (" + names + ") ORDER BY ts_ms"
    )
    series = {}
    for row in rows:
        stamps, values = series.setdefault(row["signal"], ([], []))
        stamps.append(float(row["ts_ms"]))
        values.append(float(row["value"]))
    return {
        name: (np.asarray(stamps), np.asarray(values))
        for name, (stamps, values) in series.items()
    }


def _history(run_id, table):
    """Every signal on one grid, the grid in seconds, and its step.

    A CAN signal is latched, so a sample of another frame reads as the last
    value at or before the instant. Interpolating would invent a state the bus
    never held.
    """
    series = _series(run_id, table)
    missing = [name for name in SIGNALS if name not in series]
    if missing:
        raise LookupError(f"run {run_id} carries none of {missing} in {table}")

    grid = series[SIGNALS[0]][0]
    history = {}
    for name in SIGNALS:
        stamps, values = series[name]
        index = np.clip(
            np.searchsorted(stamps, grid, side="right") - 1, 0, len(values) - 1
        )
        history[name] = values[index]
    times = (grid - grid[0]) / 1000.0
    return history, times, float(np.median(np.diff(times)))


def _measure(history, times, dt_s):
    """The achieved numbers, keyed as `out/manifest.csv` keys them."""
$measure


def _passed(evidence):
    """$rule"""
    return (
        $passes
    )


def evaluate(run_id, table="battery_data_v1"):
    """Answer one verdict for one run.

    `table` is the lake table that holds the run's samples. The registry records
    it per run as `lake_table`, so a run outlives a table bump with its pointer
    intact.
    """
    history, times, dt_s = _history(run_id, table)
    evidence = _measure(history, times, dt_s)
    return {
        "tc_id": TC_ID,
        "run_id": run_id,
        "verdict": "PASS" if _passed(evidence) else "FAIL",
        "evidence": evidence,
    }
'''
)


def _literal(value) -> str:
    """Render one Python literal. JSON and Python agree on lists and dicts here."""
    return json.dumps(value, indent=4)


def render(tc_id: str) -> str:
    """The whole module source of one test implementation."""
    case = CASES[tc_id]
    spec = sources.test_specs()[tc_id]
    states = "".join(
        f"\n#: `BMS_State` = {BMS_STATE[name]} (`controller/state_machine.py`).\n"
        f"{name} = {BMS_STATE[name]}\n"
        for name in case.states
    )
    return _TEMPLATE.substitute(
        tc_id=tc_id,
        title=spec["title"],
        req_ids=", ".join(spec["covers_req_ids"]),
        req_id_list=_literal(list(spec["covers_req_ids"])),
        signal_list=_literal(list(case.signals)),
        limits=_literal(case.limits),
        states=states,
        rule=case.rule,
        measure=case.measure,
        passes=case.passes,
    )


def write_all(out_dir: Path = OUT_DIR) -> dict[str, Path]:
    """Write the ten modules. Returns `{tc_id: path}`."""
    out_dir.mkdir(parents=True, exist_ok=True)
    written = {}
    for tc_id in sorted(CASES):
        path = out_dir / f"{tc_id}.py"
        path.write_text(render(tc_id), encoding="utf-8")
        written[tc_id] = path
    return written


def upload_all(out_dir: Path = OUT_DIR) -> dict[str, dict]:
    """Render, then POST each module to its definition. Returns the answers."""
    return {
        tc_id: push.implementation(tc_id, path)
        for tc_id, path in write_all(out_dir).items()
    }
